### ISSUE TITLE
コメント内に ; が含まれているとパースに失敗する

### ISSUE THREAD

**Issue by snakazawa** [givery-technology/track-db-test-library#22]
以下のようなSQLを入力したとします。

```
-- ; abc
select * from hoge;
```

すると、以下のようなエラーが発生します。

```
node /home/postgres/node_modules/track-db-test-library/bin/run-sql.js exec --client postgres < "sql/main.sql"
SQL 実行結果:
  --

  0 件が選択されました
  レコードが選択されていません
  
error: syntax error at or near "abc"
    at Parser.parseErrorMessage (/home/postgres/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/postgres/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/postgres/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/postgres/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 91,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '1',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1145',
  routine: 'scanner_yyerror'
}
```

おそらく、 `;` で split しているためだと思います。
SQL中のコメント部分を削除した後に split をする必要があると思います。コメントは `/* */` でも書けるため注意が必要です。

**Comment by a-miyashita** [comment]
なるほど、run-sql.js 経由だと parseSQL を通過しないのか
https://github.com/givery-technology/track-db-test-library/blob/ac0ad9d5c30d543e4314adf2670168a401103533/lib/connection.js#L35

【修正方針】

* parseSQL をブロックコメントに対応
* run-sql から parseSQL を呼び出す

**Comment by a-miyashita** [comment]
`run-sql` は deprecated にしているので、`track-db` コマンドを使う

```
node /home/postgres/node_modules/track-db-test-library/bin/track-db.js debug --client postgres < "sql/main.sql"
```

で、こっちをいろいろ対応させる

**Comment by a-miyashita** [comment]
あ、`run-sql` も顧客納品物で使っていたのか。。。じゃあ仕方ない、修正するか。
